// Generated by gencpp from file LR_ARMs/arm.msg
// DO NOT EDIT!


#ifndef LR_ARMS_MESSAGE_ARM_H
#define LR_ARMS_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace LR_ARMs
{
template <class ContainerAllocator>
struct arm_
{
  typedef arm_<ContainerAllocator> Type;

  arm_()
    : r1(0.0)
    , r2(0.0)
    , r3(0.0)
    , l1(0.0)
    , l2(0.0)
    , l3(0.0)  {
    }
  arm_(const ContainerAllocator& _alloc)
    : r1(0.0)
    , r2(0.0)
    , r3(0.0)
    , l1(0.0)
    , l2(0.0)
    , l3(0.0)  {
  (void)_alloc;
    }



   typedef float _r1_type;
  _r1_type r1;

   typedef float _r2_type;
  _r2_type r2;

   typedef float _r3_type;
  _r3_type r3;

   typedef float _l1_type;
  _l1_type l1;

   typedef float _l2_type;
  _l2_type l2;

   typedef float _l3_type;
  _l3_type l3;




  typedef boost::shared_ptr< ::LR_ARMs::arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::LR_ARMs::arm_<ContainerAllocator> const> ConstPtr;

}; // struct arm_

typedef ::LR_ARMs::arm_<std::allocator<void> > arm;

typedef boost::shared_ptr< ::LR_ARMs::arm > armPtr;
typedef boost::shared_ptr< ::LR_ARMs::arm const> armConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::LR_ARMs::arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::LR_ARMs::arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace LR_ARMs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'LR_ARMs': ['/home/kogaku/hogehoge_ws/src/LR_ARMs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::LR_ARMs::arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::LR_ARMs::arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::LR_ARMs::arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::LR_ARMs::arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::LR_ARMs::arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::LR_ARMs::arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::LR_ARMs::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebcb7d1662e4c1ce1cf5e4dd34b32042";
  }

  static const char* value(const ::LR_ARMs::arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebcb7d1662e4c1ceULL;
  static const uint64_t static_value2 = 0x1cf5e4dd34b32042ULL;
};

template<class ContainerAllocator>
struct DataType< ::LR_ARMs::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LR_ARMs/arm";
  }

  static const char* value(const ::LR_ARMs::arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::LR_ARMs::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 r1\n\
float32 r2\n\
float32 r3\n\
float32 l1\n\
float32 l2\n\
float32 l3\n\
";
  }

  static const char* value(const ::LR_ARMs::arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::LR_ARMs::arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r1);
      stream.next(m.r2);
      stream.next(m.r3);
      stream.next(m.l1);
      stream.next(m.l2);
      stream.next(m.l3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::LR_ARMs::arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::LR_ARMs::arm_<ContainerAllocator>& v)
  {
    s << indent << "r1: ";
    Printer<float>::stream(s, indent + "  ", v.r1);
    s << indent << "r2: ";
    Printer<float>::stream(s, indent + "  ", v.r2);
    s << indent << "r3: ";
    Printer<float>::stream(s, indent + "  ", v.r3);
    s << indent << "l1: ";
    Printer<float>::stream(s, indent + "  ", v.l1);
    s << indent << "l2: ";
    Printer<float>::stream(s, indent + "  ", v.l2);
    s << indent << "l3: ";
    Printer<float>::stream(s, indent + "  ", v.l3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LR_ARMS_MESSAGE_ARM_H
